/* @uthor : Nathanael ROVERE & Michel YIP */

#include "../include/displayList.h"

/* Create en ID List for drawing the background */
void createDrawBackgroundIDList(GLuint textureID[TEXTURES_SIZE]){
    glNewList(ID_BACKGROUND1, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_BACKGROUND1]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(0,0);
                glTexCoord2f(1,0);
                glVertex2f(WINDOW_WIDTH,0);
                glTexCoord2f(1,1);
                glVertex2f(WINDOW_WIDTH,WINDOW_HEIGHT);
                glTexCoord2f(0,1);
                glVertex2f(0,WINDOW_HEIGHT);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_BACKGROUND2, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_BACKGROUND2]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(0,0);
                glTexCoord2f(1,0);
                glVertex2f(WINDOW_WIDTH,0);
                glTexCoord2f(1,1);
                glVertex2f(WINDOW_WIDTH,WINDOW_HEIGHT);
                glTexCoord2f(0,1);
                glVertex2f(0,WINDOW_HEIGHT);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
}

/* Create an ID List for drawing an unit */
void createDrawUnitIDList(GLuint textureID[TEXTURES_SIZE]){
    glNewList(ID_PLAYER1, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_PLAYER1]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-ELEM_SIZE/2,-ELEM_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(ELEM_SIZE/2,-ELEM_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(ELEM_SIZE/2,ELEM_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-ELEM_SIZE/2,ELEM_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_PLAYER2, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_PLAYER2]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-ELEM_SIZE/2,-ELEM_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(ELEM_SIZE/2,-ELEM_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(ELEM_SIZE/2,ELEM_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-ELEM_SIZE/2,ELEM_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_ENEMY, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_ENEMY]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-ELEM_SIZE/2,-ELEM_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(ELEM_SIZE/2,-ELEM_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(ELEM_SIZE/2,ELEM_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-ELEM_SIZE/2,ELEM_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_BOSS, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_BOSS]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-BOSS_SIZE/2,-BOSS_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(BOSS_SIZE/2,-BOSS_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(BOSS_SIZE/2,BOSS_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-BOSS_SIZE/2,BOSS_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
}

/* Create an ID List for drawing a projectile */
void createDrawProjectileIDList(GLuint textureID[TEXTURES_SIZE]){
    glNewList(ID_PROJECTILE_PLAYER, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_PROJECTILE_PLAYER]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_PROJECTILE_ENEMY, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_PROJECTILE_ENEMY]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_PROJECTILE_ENEMY+1, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_PROJECTILE_ENEMY+1]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_PROJECTILE_ENEMY+2, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_PROJECTILE_ENEMY+2]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_PROJECTILE_ENEMY+3, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_PROJECTILE_ENEMY+3]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_PROJECTILE_ENEMY+4, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_PROJECTILE_ENEMY+4]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(PROJECTILE_SIZE/2,-PROJECTILE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-PROJECTILE_SIZE/2,PROJECTILE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
}

/* Create an ID List for drawing a bonus */
void createDrawBonusIDList(GLuint textureID[TEXTURES_SIZE]){
    glNewList(ID_BONUS_HEART, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_BONUS_HEART]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-BONUS_SIZE/2,-BONUS_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(BONUS_SIZE/2,-BONUS_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(BONUS_SIZE/2,BONUS_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-BONUS_SIZE/2,BONUS_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_BONUS_FIRE, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_BONUS_FIRE]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-BONUS_SIZE/2,-BONUS_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(BONUS_SIZE/2,-BONUS_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(BONUS_SIZE/2,BONUS_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-BONUS_SIZE/2,BONUS_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
}

/* Create an ID List for drawing a terminal */
void createDrawTerminalIDList(GLuint textureID[TEXTURES_SIZE]){
    glNewList(ID_TERMINAL, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_TERMINAL]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-TERMINAL_SIZE/2,-TERMINAL_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(TERMINAL_SIZE/2,-TERMINAL_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(TERMINAL_SIZE/2,TERMINAL_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-TERMINAL_SIZE/2,TERMINAL_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_BARRIER, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_BARRIER]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-BARRIER_WIDTH/2,-BARRIER_HEIGHT/2);
                glTexCoord2f(1,0);
                glVertex2f(BARRIER_WIDTH/2,-BARRIER_HEIGHT/2);
                glTexCoord2f(1,1);
                glVertex2f(BARRIER_WIDTH/2,BARRIER_HEIGHT/2);
                glTexCoord2f(0,1);
                glVertex2f(-BARRIER_WIDTH/2,BARRIER_HEIGHT/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
}

/* Create an ID List for drawing an obstacle */
void createDrawObstacleIDList(GLuint textureID[TEXTURES_SIZE]){
    glNewList(ID_WALL, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_WALL]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_WALL+1, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_WALL+1]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_WALL+2, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_WALL+2]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_WALL+3, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_WALL+3]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_WALL+4, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_WALL+4]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(OBSTACLE_SIZE/2,-OBSTACLE_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-OBSTACLE_SIZE/2,OBSTACLE_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
}

/* Create an ID List for drawing the UI */
void createDrawUIIDList(GLuint textureID[TEXTURES_SIZE]){
    glNewList(ID_UI_HEART, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_UI_HEART]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-UI_SIZE/2,-UI_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(UI_SIZE/2,-UI_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(UI_SIZE/2,UI_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-UI_SIZE/2,UI_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_UI_BULLET, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_UI_BULLET]);
        glPushMatrix();
            glRotatef(30,0,0,1);
            glScalef(1.5,1.5,0);
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-UI_SIZE/2,-UI_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(UI_SIZE/2,-UI_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(UI_SIZE/2,UI_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-UI_SIZE/2,UI_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
}

/* Create an ID List for drawing the title screens, game over and victory */
void createDrawMenusScreenIDList(GLuint textureID[TEXTURES_SIZE]){
    glNewList(ID_TITLE_SCREEN, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_TITLE_SCREEN]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(0,0);
                glTexCoord2f(1,0);
                glVertex2f(WINDOW_WIDTH,0);
                glTexCoord2f(1,1);
                glVertex2f(WINDOW_WIDTH,WINDOW_HEIGHT);
                glTexCoord2f(0,1);
                glVertex2f(0,WINDOW_HEIGHT);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_VICTORY_SCREEN, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_VICTORY_SCREEN]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(0,0);
                glTexCoord2f(1,0);
                glVertex2f(WINDOW_WIDTH,0);
                glTexCoord2f(1,1);
                glVertex2f(WINDOW_WIDTH,WINDOW_HEIGHT);
                glTexCoord2f(0,1);
                glVertex2f(0,WINDOW_HEIGHT);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_GAME_OVER_SCREEN, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_GAME_OVER_SCREEN]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(0,0);
                glTexCoord2f(1,0);
                glVertex2f(WINDOW_WIDTH,0);
                glTexCoord2f(1,1);
                glVertex2f(WINDOW_WIDTH,WINDOW_HEIGHT);
                glTexCoord2f(0,1);
                glVertex2f(0,WINDOW_HEIGHT);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
    glNewList(ID_ARROW, GL_COMPILE);
        glEnable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, textureID[ID_ARROW]);
        glPushMatrix();
            glBegin(GL_QUADS);
                glTexCoord2f(0,0);
                glVertex2f(-ELEM_SIZE/2,-ELEM_SIZE/2);
                glTexCoord2f(1,0);
                glVertex2f(ELEM_SIZE/2,-ELEM_SIZE/2);
                glTexCoord2f(1,1);
                glVertex2f(ELEM_SIZE/2,ELEM_SIZE/2);
                glTexCoord2f(0,1);
                glVertex2f(-ELEM_SIZE/2,ELEM_SIZE/2);
            glEnd();
        glPopMatrix();
        glDisable(GL_TEXTURE_2D);
        glBindTexture(GL_TEXTURE_2D, 0);
    glEndList();
}